# Generated by Django 3.1.13 on 2021-07-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='track_id',
            new_name='track',
        ),
    ]
