# Generated by Django 3.1.13 on 2021-07-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_artist_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
