# Generated by Django 3.1.13 on 2021-07-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210715_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='media_type_id',
            new_name='mediatype',
        ),
    ]
