# Generated by Django 3.1.13 on 2021-07-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210715_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='milli_seconds',
            new_name='milliseconds',
        ),
    ]
